### ISSUE TITLE
Integration producing system log errors

### ISSUE THREAD

**Issue by w1Ngx** [eifinger/hass-weenect#321] opened 2023-10-03 11:40 UTC
Hi,

I am using the weenect integration, but for some reason I get a lot of errors recently.
The udpate is not working and just randomly updates the position of the tracker.

This is one of the most recent errors:

Logger: homeassistant
Source: util/dt.py:192
First occurred: 1:27:39 PM (17 occurrences)
Last logged: 1:35:39 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 469, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 473, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weenect/sensor.py", line 148, in native_value
    return dt.parse_datetime(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 192, in parse_datetime
    return ciso8601.parse_datetime(dt_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument must be str

**Comment by eifinger** [comment] 2023-10-05 09:15
Altough this looks different this is a duplicate of #318

**Closed by eifinger** 2023-10-05 09:15 UTC
